name: Deploy Production

on:
  push:
    branches:
      - master

jobs:
  install: # Runs install once before everything to create & save cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-deploy-production-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-deploy-production-
            ${{ runner.os }}-
      - run: yarn install
  deploy:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-deploy-production-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-deploy-production-
            ${{ runner.os }}-
      - run: yarn install
      - name: publish
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
